import {
    Accessibility,
    ArrowUpCircle,
    Baby,
    Bath,
    Car,
    Coffee,
    Dumbbell,
    Flame,
    Mic2,
    Mountain,
    Palmtree,
    PawPrint,
    Plane,
    Sparkles,
    Umbrella,
    Users,
    Utensils,
    Waves,
    Wifi,
    Wind,
    Wine,
    HelpCircle,
    CheckCircle,
    type LucideIcon,
} from 'lucide-react';

const FACILITY_ICON_MAP: Record<string, LucideIcon> = {
    Accessibility,
    ArrowUpCircle,
    Baby,
    Bath,
    Car,
    Coffee,
    Dumbbell,
    Flame,
    Mic2,
    Mountain,
    Palmtree,
    PawPrint,
    Plane,
    Sparkles,
    Umbrella,
    Users,
    Utensils,
    Waves,
    Wifi,
    Wind,
    Wine,
    HelpCircle,
    CheckCircle,
};

export function getFacilityIcon(name: string, fallback: 'HelpCircle' | 'CheckCircle' = 'HelpCircle'): LucideIcon {
    return FACILITY_ICON_MAP[name] || FACILITY_ICON_MAP[fallback];
}
